spring:
  application:
    name: habit-tracker
  config:
    import: "classpath:.secrets.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/habit-tracker?useTimezone=true&serverTimezone=UTC
    username: ${dbusername}
    password: ${dbpassword}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring-doc:
  paths-to-match:
    - /v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true